services:
  stats-server:
    build: stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345
  stats-db:
    image: postgres:16.1
    ports:
      - "9432:5432"
    environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=stats_db

  ewm-service:
    build: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=12345

  ewm-db:
    image: postgres:16.1
    ports:
      - "9433:5432"
    environment:
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=12345
     - POSTGRES_DB=ewm_db
